services:
  barracuda-control:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-control
    user: root
    privileged: true
    tty: true
    network_mode: host
    ports:
      - 8765:8765
    volumes:
      - ${PWD}:/opt/barracuda-control
