lqr:
  update_rate: 50
  Q: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0]
  R: [1, 1, 1, 1, 1, 1]

target_pose:
  position:
    x: 3.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 3.14
