lqr:
  update_rate: 50
  Q: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  R: [1, 1, 1, 1, 1, 1]
  M_t: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  I_rot: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  D_t: [0, 0, 0, 0, 0, 0, 0, 0, 0]
  D_r: [0, 0, 0, 0, 0, 0, 0, 0, 0]

target_pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
