lqr:
  update_rate: 50
  Q: [50, 50, 50, 40, 40, 40, 20, 20, 20, 15, 15, 30]
  R: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  M_t: [36.3, 0, 0,
        0, 36.3, 0,
        0, 0, 36.3]
  I_rot: [2.5, 0, 0,
          0, 8.0, 0,
          0, 0, 8.5]
  D_t: [15, 0, 0,
        0, 12, 0,
        0, 0, 35]
  D_r: [25, 0, 0, 
        0, 20, 0,
        0, 0, 8]

target_pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 3.14
