pid:
  update_rate: 50
  Kp: [1, 1, 1, 1, 1, 1]
  Ki: [0, 0, 0, 0, 0, 0]
  Kd: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

target_pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
