services:
  barracuda-control:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: barracuda-control
    container_name: barracuda-control
    user: root
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-control-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-control-dev
    container_name: barracuda-control-dev
    tty: true
    network_mode: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../barracuda_control:/ros2_ws/src/barracuda_control
    profiles: ["dev"]
