name: Docker Publish - barracuda-control

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push barracuda-control
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/barracuda-control:latest
          docker build --no-cache -t $IMAGE_NAME ./barracuda-control
          docker push $IMAGE_NAME
